name: dockerproxy
services:
  dockerproxy:
    image: ghcr.io/tecnativa/docker-socket-proxy:latest
    container_name: Docker-Proxy
    restart: unless-stopped
    ports:
      - 2375:2375
    environment:
      - CONTAINERS=1
      - POST=0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      homepage.group: $HOMELAB_HOSTTITLE
      homepage.name: Docker Proxy
      homepage.icon: docker
