name: scanopy
services:
  scanopy:
    image: ghcr.io/scanopy/scanopy/server
    container_name: Scanopy
    restart: unless-stopped
    networks:
      - default
      - traefik
    volumes:
      - /home/pi/docker/scanopy/data:/data
    environment:
      SCANOPY_LOG_LEVEL: ${SCANOPY_LOG_LEVEL:-info}
      SCANOPY_DATABASE_URL: postgresql://scanopy:scanopy@scanopy-postgres:5432/scanopy
      SCANOPY_WEB_EXTERNAL_PATH: /app/static
#      SCANOPY_PUBLIC_URL: https://scanopy.local.$HOMELAB_DOMAIN
#      SCANOPY_INTEGRATED_DAEMON_URL: http://host.docker.internal:60073
      SCANOPY_USE_SECURE_SESSION_COOKIES: true
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_traefik
      traefik.http.routers.scanopy.entrypoints: https
      traefik.http.routers.scanopy.tls: true
      traefik.http.routers.scanopy.tls.domains[0].main: local.$HOMELAB_DOMAIN
      traefik.http.routers.scanopy.tls.domains[0].sans: '*.local.$HOMELAB_DOMAIN'
      traefik.http.routers.scanopy.rule: Host(`scanopy.local.$HOMELAB_DOMAIN`)
      traefik.http.services.scanopy.loadbalancer.server.port: 60072
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      scanopy-postgres:
        condition: service_healthy
  scanopy-postgres:
    image: postgres:17-alpine
    container_name: Scanopy-Postgres
    restart: unless-stopped
#    networks:
#      - scanopy
    volumes:
      - /home/pi/docker/scanopy/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: scanopy
      POSTGRES_USER: scanopy
      POSTGRES_PASSWORD: scanopy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scanopy"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
#  scanopy:
#    driver: bridge
#    ipam:
#      config:
#        - subnet: 172.31.0.0/16
#          gateway: 172.31.0.1networks:
  traefik:
    external: true
    name: traefik_traefik
