# from https://github.com/paperless-ngx/paperless-ngx/tree/dev/docker/compose

name: paperless
services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: Paperless
    restart: unless-stopped
    depends_on:
      - broker
    ports:
      - "8000:8000"
#    networks:
#      - traefik
    volumes:
      - /home/pi/docker/paperless/data:/usr/src/paperless/data
      - /home/pi/docker/paperless/media:/usr/src/paperless/media
      - /home/pi/docker/paperless/export:/usr/src/paperless/export
      - /home/pi/docker/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
# The UID and GID of the user used to run paperless in the container. Set this
# to your UID and GID on the host so that you have write access to the
# consumption directory.
      UID: 1000
      GID: 100
      USERMAP_UID: 1000
      USERMAP_GID: 100
      PAPERLESS_OCR_LANGUAGES: deu eng
      PAPERLESS_OCR_LANGUAGE: deu
      # This is required if you will be exposing Paperless-ngx on a public domain
      # (if doing so please consider security measures such as reverse proxy)
      #PAPERLESS_URL=https://paperless.example.com
      # Adjust this key if you plan to make paperless available publicly. It should
      # be a very long sequence of random characters. You don't need to remember it.
      #PAPERLESS_SECRET_KEY=change-me
  broker:
    image: docker.io/library/redis:7
    container_name: Paperless-Redis
    restart: unless-stopped
    volumes:
      - redisdata:/data
  db:
    image: docker.io/library/postgres:16
    container_name: Paperless-Postgres
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

volumes:
  data:
  media:
  pgdata:
  redisdata:
