# from https://github.com/paperless-ngx/paperless-ngx/tree/dev/docker/compose

name: paperless
services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: Paperless
    restart: unless-stopped
    depends_on:
      - paperless-db
      - paperless-broker
    networks:
      - default
      - traefik
    ports:
      - "8000:8000"
    volumes:
      - /home/pi/docker/paperless/data:/usr/src/paperless/data
      - /home/pi/docker/paperless/media:/usr/src/paperless/media
      - /home/pi/docker/paperless/export:/usr/src/paperless/export
      - /home/pi/docker/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_REDIS: redis://paperless-broker:6379
      PAPERLESS_DBHOST: paperless-db
      PAPERLESS_OCR_LANGUAGES: deu eng
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_OCR_USER_ARGS='{"invalidate_digital_signatures": true}'
      PAPERLESS_URL: https://paperless.local.$HOMELAB_DOMAIN
      PAPERLESS_SECRET_KEY: $HOMELAB_PAPERLESS_KEY
      PAPERLESS_ADMIN_USER: $HOMELAB_PAPERLESS_ADMIN_USERNAME
      PAPERLESS_ADMIN_PASSWORD: $HOMELAB_PAPERLESS_ADMIN_PASSWORD
      PAPERLESS_CONSUME_DIR: /usr/src/paperless/consume
      # use for Synology
      # USERMAP_UID: 1026
      # USERMAP_GID: 100
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PUID: 1000
      PGID: 1000
      PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: >
          {
            "openid_connect": {
              "APPS": [
                {
                  "provider_id": "authentik",
                  "name": "Authentik",
                  "client_id": "$HOMELAB_AUTHENTIK_CLIENT",
                  "secret": "$HOMELAB_AUTHENTIK_SECRET",
                  "settings": {
                    "server_url": "https://authentik.local.$HOMELAB_DOMAIN/application/o/paperless/.well-known/openid-configuration"
                  }
                }
              ],
              "OAUTH_PKCE_ENABLED": "True"
            }
          }
      PAPERLESS_REDIRECT_LOGIN_TO_SSO: true
    labels:
      traefik.enable: true
      traefik.docker.network: traefik_traefik
      traefik.http.routers.paperless.entrypoints: https
      traefik.http.routers.paperless.tls: true
      traefik.http.routers.paperless.tls.domains[0].main: local.$HOMELAB_DOMAIN
      traefik.http.routers.paperless.tls.domains[0].sans: '*.local.$HOMELAB_DOMAIN'
      traefik.http.routers.paperless.rule: Host(`paperless.local.$HOMELAB_DOMAIN`)
      traefik.http.services.paperless.loadbalancer.server.port: 8000
      homepage.group: Dokumente
      homepage.name: Paperless
      homepage.icon: paperless-ngx
      homepage.href: https://paperless.local.$HOMELAB_DOMAIN
      homepage.widget.type: paperlessngx
      homepage.widget.url: https://paperless.local.$HOMELAB_DOMAIN
      homepage.widget.key: $HOMELAB_HOMEPAGE_PAPERLESS_TOKEN
  paperless-broker:
    image: docker.io/library/redis:7
    container_name: Paperless-Redis
    restart: unless-stopped
    volumes:
      - /home/pi/docker/paperless/redis:/data
  paperless-db:
    image: docker.io/library/postgres:16
    container_name: Paperless-Postgres
    restart: unless-stopped
    volumes:
      - /home/pi/docker/paperless/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
networks:
  traefik:
    external: true
    name: traefik_traefik
