name: homepage
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: Homepage
    restart: unless-stopped
#    environment:
#      PUID: 1026 #-- optional, your user id
#      PGID: 100 #-- optional, your group id
#    ports:
#      - 3000:3000
    networks:
      - traefik
    volumes:
      - /home/pi/docker/homepage:/app/config
      - /etc/localtime:/etc/localtime:ro
#      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      homepage.group: Status
      homepage.name: Homepage
      homepage.description: Dashboard
      homepage.icon: homepage
      homepage.href: https://homepage.local.$HOMELAB_DOMAIN
      traefik.enable: true
      traefik.http.routers.homepage.entrypoints: https
      traefik.http.routers.homepage.tls: true
      traefik.http.routers.homepage.tls.domains[0].main: local.$HOMELAB_DOMAIN
      traefik.http.routers.homepage.tls.domains[0].sans: "*.local.$HOMELAB_DOMAIN"
      traefik.http.routers.homepage.rule: Host(`homepage.local.$HOMELAB_DOMAIN`)
      traefik.http.services.homepage.loadbalancer.server.port: 3000
networks:
  traefik:
    external: true
    name: traefik_traefik
