# run with sudo docker compose --file portainer-agent.yml up --detach --force-recreate

name: portainer
services:
  portainer:
    image: portainer/agent:latest
    container_name: Portainer
    restart: always
    ports:
      - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    labels:
      homepage.group: $HOMELAB_HOSTTITLE
      homepage.name: Portainer-Agent
      homepage.icon: portainer
      homepage.widget.type: portainer
      homepage.widget.url: https://portainer.local.$HOMELAB_DOMAIN/#!/$HOMELAB_PORTAINER_ENV/docker/dashboard
      homepage.widget.env: $HOMELAB_PORTAINER_ENV
      homepage.widget.key: $HOMELAB_PORTAINER_KEY
