# run with sudo docker compose --file portainer-agent.yml up --detach

name: portainer      
services:
  portainer:
    image: portainer/agent:latest
    container_name: Portainer-Agent
    ports:
      - 9001:9001
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    labels:
      - homepage.group=Container
      - homepage.name=Portainer-Agent
      - homepage.icon=portainer
      - homepage.href=http://<ip>:9001
      - homepage.description=
