name: syncthing
services:
  syncthing:
    image: syncthing/syncthing
    container_name: Syncthing
    restart: unless-stopped
    ports:
#      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    networks:
      - traefik
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/pi/docker:/docker
    labels:
      homepage.group: $HOMELAB_HOSTTITLE
      homepage.name: Syncthing
      homepage.icon: syncthing
      homepage.href: http://syncthing-$HOMELAB_HOSTNAME.local.$HOMELAB_DOMAIN
      traefik.enable: true
      traefik.http.routers.syncthing.entrypoints: https
      traefik.http.routers.syncthing.tls: true
      traefik.http.routers.syncthing.tls.domains[0].main: local.$HOMELAB_DOMAIN
      traefik.http.routers.syncthing.tls.domains[0].sans: "*.local.$HOMELAB_DOMAIN"
      traefik.http.routers.syncthing.rule: Host(`syncthing-$HOMELAB_HOSTNAME.local.$HOMELAB_DOMAIN`)
      traefik.http.services.syncthing.loadbalancer.server.port: 8384
networks:
  traefik:
    external: true
    name: traefik_traefik
